version: '3.9'

services:
  movie-collection-db:
    image: postgres:17.6
    container_name: movie-collection-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=movie_collection_db
    volumes:
      - movie-collection-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - movie-collection-net

  movie-collection-backend:
    build:
      context: ./backend/MovieCollection
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - ConnectionStrings__DefaultConnection=Host=movie-collection-db;Port=5432;Database=movie_collection_db;Username=postgres;Password=postgres
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:80/swagger" ]
      interval: 10s
      timeout: 3s
      retries: 10
    depends_on:
      - movie-collection-db
    networks:
      - movie-collection-net

  movie-collection-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - API_BASE_URL=http://localhost:8080
    ports:
      - "5173:80"
    depends_on:
      movie-collection-backend:
        condition: service_started
    networks:
      - movie-collection-net

volumes:
  movie-collection-db:

networks:
  movie-collection-net:
    name: movie-collection-net